package com.logicify.screenups.common;

/**
 * Allows to implement post processors which will be applied for each frame generated by <code>FrameSource</code>
 * It can be handy way to draw some additional information on the image.
 * Created by LOGICIFY\corvis on 7/12/14.
 */
public interface FrameProcessor {
    /**
     * Performs post-processing of the given frame.
     *
     * @param frame
     */
    void processFrame(Frame frame);
}
